version: '3.8'

services:
  backend:
    build: ../../Part1/Exercise1.13
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080

  frontend:
    build: ../../Part1/Exercise1.12
    ports: 
      - 5000:5000

  redis:
    image: redis