version: '3.8'

services:
  backend:
    build: ../../Part1/Exercise1.13
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=*

    depends_on:
      - db

  frontend:
    build: .

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80