version: '3.8'

services:
  backend:
    build: ../../Part1/Exercise1.13
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    build: ../../Part1/Exercise1.12
    ports: 
      - 5000:5000

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data/