name: Release Node.js app

on:
  push:
    branches:
      - main
    paths:
      - 'Part3/Exercise3.1/express-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Part3/Exercise3.1/express-app
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: Part3/Exercise3.1/express-app
          push: true
          tags: a2742eb2a0e916c64554fd6144d8a7/express-app:latest

      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}